## A. Mengimpor _package_ yang diperlukan

In [1]:
import pandas as pd

## B. Mengeksplorasi isi data

#### 1. Melihat dataframe

In [2]:
df = pd.read_csv('covid_19_data.csv')
df

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
16724,16725,04/19/2020,Wyoming,US,2020-04-19 23:49:05,313.0,2.0,0.0
16725,16726,04/19/2020,Xinjiang,Mainland China,2020-04-19 23:49:05,76.0,3.0,73.0
16726,16727,04/19/2020,Yukon,Canada,2020-04-19 23:49:05,9.0,0.0,0.0
16727,16728,04/19/2020,Yunnan,Mainland China,2020-04-19 23:49:05,184.0,2.0,178.0
16728,16729,04/19/2020,Zhejiang,Mainland China,2020-04-19 23:49:05,1268.0,1.0,1247.0

#### 2. Mengecek data null

In [3]:
df.isna().sum()

SNo                   0
ObservationDate       0
Province/State     8372
Country/Region        0
Last Update           0
Confirmed             0
Deaths                0
Recovered             0
dtype: int64

#### 3. Melihat tipe data setiap kolom

In [4]:
df.dtypes

SNo                  int64
ObservationDate     object
Province/State      object
Country/Region      object
Last Update         object
Confirmed          float64
Deaths             float64
Recovered          float64
dtype: object

## C. Konversi susunan kolom

#### 1. Mengkonversi susunan kolom _Confirmed_, _Cases_, dan _Recovered_ agar hanya menjadi 1 kolom

In [6]:
df = df.melt(id_vars=['SNo', 'ObservationDate', 'Province/State', 'Country/Region', 'Last Update'], 
        var_name="Cases", 
        value_name="Counted")
df

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Cases,Counted
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,Confirmed,1.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,Confirmed,14.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,Confirmed,6.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,Confirmed,1.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,Confirmed,0.0
...,...,...,...,...,...,...,...
50182,16725,04/19/2020,Wyoming,US,2020-04-19 23:49:05,Recovered,0.0
50183,16726,04/19/2020,Xinjiang,Mainland China,2020-04-19 23:49:05,Recovered,73.0
50184,16727,04/19/2020,Yukon,Canada,2020-04-19 23:49:05,Recovered,0.0
50185,16728,04/19/2020,Yunnan,Mainland China,2020-04-19 23:49:05,Recovered,178.0
50186,16729,04/19/2020,Zhejiang,Mainland China,2020-04-19 23:49:05,Recovered,1247.0

#### 2. Menyimpan dataframe ke file csv

In [7]:
df.to_csv('covid_19_melted.csv', index=False)